name: UI Status Check 🤠

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  # This workflow contains a job called "Trigger Jenkins"
  status_check:
    name: Status Check
    runs-on: ubuntu-latest
    steps:
      - name: Trigger jenkins status check job
        uses: joshlk/jenkins-githubaction@master
        id: jenkins
        with:
          url: "http://jenkins-binary.centralindia.cloudapp.azure.com:8080/"
          job_name: "cricker-ui-pre-deploy-check"
          username: "binarybug"
          timeout: "900"
          interval: "30"
          api_token: ${{ secrets.JENKINS_TOKEN }}
